//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelShSy.Localization.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Errors {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ExcelShSy.Localization.Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string NoFetchShops {
            get {
                return ResourceManager.GetString("NoFetchShops", resourceCulture);
            }
        }
        
        internal static string ShopNotFound {
            get {
                return ResourceManager.GetString("ShopNotFound", resourceCulture);
            }
        }
        
        internal static string CloseWarning {
            get {
                return ResourceManager.GetString("CloseWarning", resourceCulture);
            }
        }
        
        internal static string CloseWarningText {
            get {
                return ResourceManager.GetString("CloseWarningText", resourceCulture);
            }
        }
        
        internal static string NoShopFile {
            get {
                return ResourceManager.GetString("NoShopFile", resourceCulture);
            }
        }
        
        internal static string NoShopFileText {
            get {
                return ResourceManager.GetString("NoShopFileText", resourceCulture);
            }
        }
        
        internal static string ShopExist {
            get {
                return ResourceManager.GetString("ShopExist", resourceCulture);
            }
        }
        
        internal static string ShopExistText {
            get {
                return ResourceManager.GetString("ShopExistText", resourceCulture);
            }
        }
    }
}
