//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelShSy.Localization.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainWindow {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainWindow() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ExcelShSy.Localization.Resources.MainWindow", typeof(MainWindow).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        public static string ExecuteTasks {
            get {
                return ResourceManager.GetString("ExecuteTasks", resourceCulture);
            }
        }
        
        public static string GetSourceFile {
            get {
                return ResourceManager.GetString("GetSourceFile", resourceCulture);
            }
        }
        
        public static string GetTargetFile {
            get {
                return ResourceManager.GetString("GetTargetFile", resourceCulture);
            }
        }
        
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        public static string DiscountDate {
            get {
                return ResourceManager.GetString("DiscountDate", resourceCulture);
            }
        }
        
        public static string IncreasePricePercent {
            get {
                return ResourceManager.GetString("IncreasePricePercent", resourceCulture);
            }
        }
        
        public static string RoundUp {
            get {
                return ResourceManager.GetString("RoundUp", resourceCulture);
            }
        }
        
        public static string SyncAvailability {
            get {
                return ResourceManager.GetString("SyncAvailability", resourceCulture);
            }
        }
        
        public static string SyncDiscount {
            get {
                return ResourceManager.GetString("SyncDiscount", resourceCulture);
            }
        }
        
        public static string SyncPrice {
            get {
                return ResourceManager.GetString("SyncPrice", resourceCulture);
            }
        }
        
        public static string SyncQuantity {
            get {
                return ResourceManager.GetString("SyncQuantity", resourceCulture);
            }
        }
        
        public static string EditFiles {
            get {
                return ResourceManager.GetString("EditFiles", resourceCulture);
            }
        }
        
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        public static string LastFile {
            get {
                return ResourceManager.GetString("LastFile", resourceCulture);
            }
        }
        
        public static string FindMissing {
            get {
                return ResourceManager.GetString("FindMissing", resourceCulture);
            }
        }
        
        public static string NoSetExecute_ {
            get {
                return ResourceManager.GetString("NoSetExecute_", resourceCulture);
            }
        }
        
        public static string NoSetExecuteTitle_ {
            get {
                return ResourceManager.GetString("NoSetExecuteTitle_", resourceCulture);
            }
        }
        
        public static string AboutApp {
            get {
                return ResourceManager.GetString("AboutApp", resourceCulture);
            }
        }
        
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        public static string Guid {
            get {
                return ResourceManager.GetString("Guid", resourceCulture);
            }
        }
        
        public static string Database {
            get {
                return ResourceManager.GetString("Database", resourceCulture);
            }
        }
    }
}
