//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelShSy.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainWindow {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainWindow() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExcelShSy.Localization.Resources.MainWindow", typeof(MainWindow).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Information.
        /// </summary>
        public static string AboutApp {
            get {
                return ResourceManager.GetString("AboutApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migrate discount date.
        /// </summary>
        public static string DiscountDate {
            get {
                return ResourceManager.GetString("DiscountDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit....
        /// </summary>
        public static string EditFiles {
            get {
                return ResourceManager.GetString("EditFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute.
        /// </summary>
        public static string ExecuteTasks {
            get {
                return ResourceManager.GetString("ExecuteTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find missing.
        /// </summary>
        public static string FindMissing {
            get {
                return ResourceManager.GetString("FindMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add source file.
        /// </summary>
        public static string GetSourceFile {
            get {
                return ResourceManager.GetString("GetSourceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add target file.
        /// </summary>
        public static string GetTargetFile {
            get {
                return ResourceManager.GetString("GetTargetFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instruction.
        /// </summary>
        public static string Guid {
            get {
                return ResourceManager.GetString("Guid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase price (fake discount).
        /// </summary>
        public static string IncreasePricePercent {
            get {
                return ResourceManager.GetString("IncreasePricePercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last file.
        /// </summary>
        public static string LastFile {
            get {
                return ResourceManager.GetString("LastFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select any execute.
        /// </summary>
        public static string NoSetExecute_ {
            get {
                return ResourceManager.GetString("NoSetExecute_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No selected execute.
        /// </summary>
        public static string NoSetExecuteTitle_ {
            get {
                return ResourceManager.GetString("NoSetExecuteTitle_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round up prices.
        /// </summary>
        public static string RoundUp {
            get {
                return ResourceManager.GetString("RoundUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migrate availability.
        /// </summary>
        public static string SyncAvailability {
            get {
                return ResourceManager.GetString("SyncAvailability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migrate discount.
        /// </summary>
        public static string SyncDiscount {
            get {
                return ResourceManager.GetString("SyncDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migrate prices.
        /// </summary>
        public static string SyncPrice {
            get {
                return ResourceManager.GetString("SyncPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migrate quantity.
        /// </summary>
        public static string SyncQuantity {
            get {
                return ResourceManager.GetString("SyncQuantity", resourceCulture);
            }
        }
    }
}
