name: Build

on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux-x64, win-x64]
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0
        
    - name: Restore
      run: dotnet restore
      
    - name: Build
      run: dotnet build
      
    - name: Publish
      run: dotnet publish -c Release -r ${{ matrix.os }} /p:PublishSingleFile=false -o ./publish/${{ matrix.os }}
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ExShSy-${{ matrix.os }}
        path: ./publish/${{ matrix.os }}
