name: Build

on:
  push:
    tags: [ "v*" ]
    paths-ignore:
      - "**/*.md"
      - "**/*.gitignore"
      - "**/*.gitattributes"
  workflow_dispatch:
  release:
    types: [created]


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux-x64, win-x64]
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.0.x
          
      - name: Restore
        run: dotnet restore
        
      - name: Build
        run: dotnet build
        
      - name: Publish Setup
        run: dotnet publish ./ExcelShSy.Setup/ExcelShSy.Setup.csproj -c Release -r ${{ matrix.os }} --self-contained true /p:PublishSingleFile=true -o ./publish/${{ matrix.os }}

      - name: Publish UI
        run: dotnet publish ./ExcelShSy.Ui/ExcelShSy.Ui.csproj -c Release -r ${{ matrix.os }} --self-contained true /p:PublishSingleFile=true -o ./publish/${{ matrix.os }}
        
      - name: Archive output
        run: |
          cd publish/${{ matrix.os }}
          if [[ "${{ matrix.os }}" == "win-x64" ]]; then
            zip -r ../../ExShSy-${{ matrix.os }}.zip .
          else
            tar -czf ../../ExShSy-${{ matrix.os }}.tar.gz .
          fi
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ExShSy-${{ matrix.os }}
          path: ExShSy-${{ matrix.os }}.*

  release:
    runs-on: ubuntu-latest
    needs: build
    
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./artifacts
  
    - name: Get version from project
      id: get_version
      run: |
        # Предполагая, что версия в .csproj файле
        VERSION=$(grep -oP '<Version>\K[^<]+' *.csproj | head -1)
        echo "version=$VERSION" >> $GITHUB_OUTPUT
  
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ steps.get_version.outputs.version }}
        name: Release v${{ steps.get_version.outputs.version }}
        files: |
          ./artifacts/ExShSy-win-x64/ExShSy-win-x64.zip
          ./artifacts/ExShSy-linux-x64/ExShSy-linux-x64.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
